name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      fail-fast: false
      matrix:
        deno-version: ["v1.11", "v1.12", "v1.13", "canary"]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https:// deps
      uses: actions/cache@v2
      with:
        path: ~/.cache/deno/deps/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno/${{ matrix.deno-version }}-https/v1-

    - name: Check generation/deploy/mod.ts
      run: time deno cache generation/deploy/mod.ts

    - name: Check client/mod.ts
      run: time deno cache lib/client/mod.ts

    - name: Check demo.ts
      run: time deno cache lib/demo.ts

  generate:
    runs-on: ubuntu-latest

    name: Codegen w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version: ["v1.11", "v1.13", "canary"]
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source, incl aws-sdk-js
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https:// deps
      uses: actions/cache@v2
      with:
        path: ~/.cache/deno/deps/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno/${{ matrix.deno-version }}-https/v1-

    - name: Validate aws-sdk fixtures
      run: time deno run -A generation/script/validate-fixtures.ts

    - name: Validate all aws-sdk services
      run: time deno run -A generation/script/validate-services.ts
