name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Basic checks w/ ${{ matrix.deno-version }}
    strategy:
      fail-fast: false
      matrix:
        deno-version:
        - v2.0
        - v2.1
        - v2.2
        - v2.3
        - v2.4

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https:// deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno/deps/https
          ~/.cache/deno/remote/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno/${{ matrix.deno-version }}-https/v1-

    - name: Check client/mod.ts
      if: always()
      run: time deno check lib/client/mod.ts

    - name: Check demo.ts
      if: always()
      run: time deno check lib/demo.ts

    - name: Run tests
      if: always()
      run: >
        time deno test
        --allow-net=169.254.169.254,example.com
        --allow-env
        lib/client/
        lib/encoding/
        lib/extras/

  check-publish:
    runs-on: ubuntu-latest
    name: Check JSR Publish

    steps:
    - uses: denoland/setup-deno@v2
    - uses: actions/checkout@v5

    - name: Check publish rules
      run: deno publish --dry-run --allow-dirty

  publish:
    runs-on: ubuntu-latest
    name: JSR Publish
    needs:
    - build
    - check-publish
    if: github.event_name == 'push'

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: denoland/setup-deno@v2
    - uses: actions/checkout@v5

    - name: Publish now
      run: deno publish

  build-web-service:
    runs-on: ubuntu-latest

    name: Web Service checks w/ ${{ matrix.deno-version }}
    strategy:
      fail-fast: false
      matrix:
        deno-version:
        - v2.1
        - v2.2
        - v2.3
        - v2.4

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https:// deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno/deps/https
          ~/.cache/deno/remote/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno/${{ matrix.deno-version }}-https/v1-

    - name: Check generation/deploy/mod.ts
      if: always()
      run: time deno check --allow-import=cdn.skypack.dev,deno.land generation/deploy/mod.ts

  validate-codegen:
    runs-on: ubuntu-latest

    name: Test codegen w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v2.0
        - v2.1
        - v2.2
        - v2.3
        - v2.4
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source, incl aws-sdk-js
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https:// deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno/deps/https
          ~/.cache/deno/remote/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno/${{ matrix.deno-version }}-https/v1-

    - name: Validate aws-sdk fixtures
      if: always()
      run: time deno run -A generation/script/validate-fixtures.ts

    - name: Validate all aws-sdk services
      if: always()
      run: time deno run -A generation/script/validate-services.ts

  regenerate-bundled:
    runs-on: ubuntu-latest

    name: Regen bundled services
    if: github.event_name == 'push'
    needs:
    - validate-codegen
    strategy:
      matrix:
        deno-version:
        - v2.4

    steps:
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        submodules: true

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https:// deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno/deps/https
          ~/.cache/deno/remote/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno/${{ matrix.deno-version }}-https/v1-

    - name: Regenerate API files
      run: time ./generation/script/update-all.sh

    - name: Perhaps create PR
      uses: peter-evans/create-pull-request@v7
      with:
        branch: regen-bundled-services
        delete-branch: true
        commit-message: "chore(services): Rebuild using latest codegen"
        title: "chore(services): Rebuild using latest codegen"
